# coding: utf-8

"""
    Pollination Server

    Pollination Server OpenAPI Defintion  # noqa: E501

    The version of the OpenAPI document: 0.0.0
    Contact: info@pollination.cloud
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pollination_sdk
from pollination_sdk.models.repository_abridged_dto import RepositoryAbridgedDto  # noqa: E501
from pollination_sdk.rest import ApiException

class TestRepositoryAbridgedDto(unittest.TestCase):
    """RepositoryAbridgedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RepositoryAbridgedDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pollination_sdk.models.repository_abridged_dto.RepositoryAbridgedDto()  # noqa: E501
        if include_optional :
            return RepositoryAbridgedDto(
                description = '0', 
                icon = '0', 
                keywords = [
                    '0'
                    ], 
                latest_tag = '0', 
                name = '0', 
                owner = null, 
                public = True, 
                slug = '0'
            )
        else :
            return RepositoryAbridgedDto(
                latest_tag = '0',
                name = '0',
                owner = null,
        )

    def testRepositoryAbridgedDto(self):
        """Test RepositoryAbridgedDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
