# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.7.5
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.status_type import StatusType  # noqa: E501
from pollination_sdk.rest import ApiException


class TestStatusType(unittest.TestCase):
    """StatusType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusType(self):
        """Test StatusType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.status_type.StatusType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
