# coding: utf-8

"""
    pollination.cloud

    Pollination Cloud API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.sensor_grid_in import SensorGridIn  # noqa: E501
from pollination_sdk.rest import ApiException


class TestSensorGridIn(unittest.TestCase):
    """SensorGridIn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorGridIn(self):
        """Test SensorGridIn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.sensor_grid_in.SensorGridIn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
