# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.5.25
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.project_access_policy_dto import ProjectAccessPolicyDto  # noqa: E501
from pollination_sdk.rest import ApiException


class TestProjectAccessPolicyDto(unittest.TestCase):
    """ProjectAccessPolicyDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectAccessPolicyDto(self):
        """Test ProjectAccessPolicyDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.project_access_policy_dto.ProjectAccessPolicyDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
