# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v0.1.0-5-g8af5d0f
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.app_modules_workflows_interface_permissions import AppModulesWorkflowsInterfacePermissions  # noqa: E501
from pollination_sdk.rest import ApiException


class TestAppModulesWorkflowsInterfacePermissions(unittest.TestCase):
    """AppModulesWorkflowsInterfacePermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppModulesWorkflowsInterfacePermissions(self):
        """Test AppModulesWorkflowsInterfacePermissions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.app_modules_workflows_interface_permissions.AppModulesWorkflowsInterfacePermissions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
