# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.5.25
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.input_parameter_reference import InputParameterReference  # noqa: E501
from pollination_sdk.rest import ApiException


class TestInputParameterReference(unittest.TestCase):
    """InputParameterReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInputParameterReference(self):
        """Test InputParameterReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.input_parameter_reference.InputParameterReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
