# coding: utf-8

"""
    pollination-server

    Pollination Server OpenAPI Definition  # noqa: E501

    The version of the OpenAPI document: 0.25.0
    Contact: info@pollination.cloud
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import pollination_sdk
from pollination_sdk.models.payment_method import PaymentMethod  # noqa: E501
from pollination_sdk.rest import ApiException

class TestPaymentMethod(unittest.TestCase):
    """PaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test PaymentMethod
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = pollination_sdk.models.payment_method.PaymentMethod()  # noqa: E501
        if include_optional :
            return PaymentMethod(
                billing_details = pollination_sdk.models.billing_details.Billing Details(), 
                card = pollination_sdk.models.card.Card(
                    brand = '0', 
                    country = '0', 
                    exp_month = 56, 
                    exp_year = 56, 
                    last4 = '0', 
                    networks = pollination_sdk.models.networks.Networks(), ), 
                id = '0', 
                is_default = True, 
                metadata = pollination_sdk.models.metadata.Metadata(), 
                type = null
            )
        else :
            return PaymentMethod(
                billing_details = pollination_sdk.models.billing_details.Billing Details(),
                id = '0',
                type = null,
        )

    def testPaymentMethod(self):
        """Test PaymentMethod"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
