# coding: utf-8

"""
    pollination.cloud

    Pollination Cloud API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.argo_outputs import ArgoOutputs  # noqa: E501
from pollination_sdk.rest import ApiException


class TestArgoOutputs(unittest.TestCase):
    """ArgoOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArgoOutputs(self):
        """Test ArgoOutputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.argo_outputs.ArgoOutputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
