# coding: utf-8

"""
    pollination.cloud

    Pollination Cloud API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.sensor_grid_out import SensorGridOut  # noqa: E501
from pollination_sdk.rest import ApiException


class TestSensorGridOut(unittest.TestCase):
    """SensorGridOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSensorGridOut(self):
        """Test SensorGridOut"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.sensor_grid_out.SensorGridOut()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
