# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.5.25
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import pollination_sdk
from pollination_sdk.models.dag_task_outputs import DAGTaskOutputs  # noqa: E501
from pollination_sdk.rest import ApiException


class TestDAGTaskOutputs(unittest.TestCase):
    """DAGTaskOutputs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDAGTaskOutputs(self):
        """Test DAGTaskOutputs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pollination_sdk.models.dag_task_outputs.DAGTaskOutputs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
