# coding: utf-8

"""
    pollination.cloud

    Pollination Cloud API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pollination_sdk.configuration import Configuration


class Operator(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'name': 'str',
        'version': 'str',
        'image': 'str',
        'local': 'LocalRequirements'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'version': 'version',
        'image': 'image',
        'local': 'local'
    }

    def __init__(self, type='operator', name=None, version=None, image=None, local=None, local_vars_configuration=None):  # noqa: E501
        """Operator - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._name = None
        self._version = None
        self._image = None
        self._local = None
        self.discriminator = None

        if type is not None:
            self.type = type
        self.name = name
        if version is not None:
            self.version = version
        self.image = image
        if local is not None:
            self.local = local

    @property
    def type(self):
        """Gets the type of this Operator.  # noqa: E501


        :return: The type of this Operator.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Operator.


        :param type: The type of this Operator.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                type is not None and not re.search(r'^operator$', type)):  # noqa: E501
            raise ValueError(r"Invalid value for `type`, must be a follow pattern or equal to `/^operator$/`")  # noqa: E501

        self._type = type

    @property
    def name(self):
        """Gets the name of this Operator.  # noqa: E501

        Operator name. This name should be unique among all the operators in your workflow.  # noqa: E501

        :return: The name of this Operator.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Operator.

        Operator name. This name should be unique among all the operators in your workflow.  # noqa: E501

        :param name: The name of this Operator.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def version(self):
        """Gets the version of this Operator.  # noqa: E501

        Optional version input for operator.  # noqa: E501

        :return: The version of this Operator.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this Operator.

        Optional version input for operator.  # noqa: E501

        :param version: The version of this Operator.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def image(self):
        """Gets the image of this Operator.  # noqa: E501

        Docker image name.  # noqa: E501

        :return: The image of this Operator.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this Operator.

        Docker image name.  # noqa: E501

        :param image: The image of this Operator.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and image is None:  # noqa: E501
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image

    @property
    def local(self):
        """Gets the local of this Operator.  # noqa: E501

        An optional requirement object to specify requirements for local execution of the commands.  # noqa: E501

        :return: The local of this Operator.  # noqa: E501
        :rtype: LocalRequirements
        """
        return self._local

    @local.setter
    def local(self, local):
        """Sets the local of this Operator.

        An optional requirement object to specify requirements for local execution of the commands.  # noqa: E501

        :param local: The local of this Operator.  # noqa: E501
        :type: LocalRequirements
        """

        self._local = local

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Operator):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Operator):
            return True

        return self.to_dict() != other.to_dict()
