# coding: utf-8

"""
    Pollination Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.5.25
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pollination_sdk.configuration import Configuration


class ProjectAccessPolicyDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'subject': 'ProjectPolicySubjectDto',
        'permission': 'str'
    }

    attribute_map = {
        'subject': 'subject',
        'permission': 'permission'
    }

    def __init__(self, subject=None, permission=None, local_vars_configuration=None):  # noqa: E501
        """ProjectAccessPolicyDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._subject = None
        self._permission = None
        self.discriminator = None

        self.subject = subject
        self.permission = permission

    @property
    def subject(self):
        """Gets the subject of this ProjectAccessPolicyDto.  # noqa: E501

        The subject the access policy refers to  # noqa: E501

        :return: The subject of this ProjectAccessPolicyDto.  # noqa: E501
        :rtype: ProjectPolicySubjectDto
        """
        return self._subject

    @subject.setter
    def subject(self, subject):
        """Sets the subject of this ProjectAccessPolicyDto.

        The subject the access policy refers to  # noqa: E501

        :param subject: The subject of this ProjectAccessPolicyDto.  # noqa: E501
        :type: ProjectPolicySubjectDto
        """
        if self.local_vars_configuration.client_side_validation and subject is None:  # noqa: E501
            raise ValueError("Invalid value for `subject`, must not be `None`")  # noqa: E501

        self._subject = subject

    @property
    def permission(self):
        """Gets the permission of this ProjectAccessPolicyDto.  # noqa: E501

        The permission to associate with the policy subject. Can be one of `admin`, `contribute`, or `use`  # noqa: E501

        :return: The permission of this ProjectAccessPolicyDto.  # noqa: E501
        :rtype: str
        """
        return self._permission

    @permission.setter
    def permission(self, permission):
        """Sets the permission of this ProjectAccessPolicyDto.

        The permission to associate with the policy subject. Can be one of `admin`, `contribute`, or `use`  # noqa: E501

        :param permission: The permission of this ProjectAccessPolicyDto.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and permission is None:  # noqa: E501
            raise ValueError("Invalid value for `permission`, must not be `None`")  # noqa: E501
        allowed_values = ["admin", "contribute", "read"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and permission not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `permission` ({0}), must be one of {1}"  # noqa: E501
                .format(permission, allowed_values)
            )

        self._permission = permission

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectAccessPolicyDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ProjectAccessPolicyDto):
            return True

        return self.to_dict() != other.to_dict()
