# coding: utf-8

"""
    pollination.cloud

    Pollination Cloud API  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from pollination_sdk.configuration import Configuration


class WorkflowTaskLog(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task': 'ArgoNodeStatus',
        'logs': 'str'
    }

    attribute_map = {
        'task': 'task',
        'logs': 'logs'
    }

    def __init__(self, task=None, logs=None, local_vars_configuration=None):  # noqa: E501
        """WorkflowTaskLog - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._task = None
        self._logs = None
        self.discriminator = None

        self.task = task
        if logs is not None:
            self.logs = logs

    @property
    def task(self):
        """Gets the task of this WorkflowTaskLog.  # noqa: E501


        :return: The task of this WorkflowTaskLog.  # noqa: E501
        :rtype: ArgoNodeStatus
        """
        return self._task

    @task.setter
    def task(self, task):
        """Sets the task of this WorkflowTaskLog.


        :param task: The task of this WorkflowTaskLog.  # noqa: E501
        :type: ArgoNodeStatus
        """
        if self.local_vars_configuration.client_side_validation and task is None:  # noqa: E501
            raise ValueError("Invalid value for `task`, must not be `None`")  # noqa: E501

        self._task = task

    @property
    def logs(self):
        """Gets the logs of this WorkflowTaskLog.  # noqa: E501


        :return: The logs of this WorkflowTaskLog.  # noqa: E501
        :rtype: str
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """Sets the logs of this WorkflowTaskLog.


        :param logs: The logs of this WorkflowTaskLog.  # noqa: E501
        :type: str
        """

        self._logs = logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WorkflowTaskLog):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WorkflowTaskLog):
            return True

        return self.to_dict() != other.to_dict()
